### ISSUE TITLE
Corrections for use without NodeRed

### ISSUE THREAD

**Issue by tomlut** [Snipercaine/WLED-HomeAssistant#1]
Thank you for making the home assistant configurations available. However I found I had to make the following changes to get palettes and presets to work with home assistant without nodered:
automations:
```
- id: wled_palette
  alias: WLED Palette
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.wled_palette_list
  action:
  - service: mqtt.publish
    data_template:
      topic: wled/all/api
      payload: "{{ states('input_select.wled_palette_list') }}"

- id: wled_presets
  alias: WLED Presets
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.wled_presets
  action:
  - service: mqtt.publish
    data_template:
      topic: wled/all/api
      payload: "{{ states('input_select.wled_presets') }}"
```
input selects:
```
wled_palette_list:
  options:
    - "[FP=00] Default"
    - "[FP=01] Random Cycle"
    - "[FP=02] Primary color"
    - "[FP=03] Based on primary"
    - "[FP=04] Set colors"
    - "[FP=05] Based on set"
    - "[FP=06] Party"
    - "[FP=07] Cloud"
    - "[FP=08] Lava"
    - "[FP=09] Ocean"
    - "[FP=10] Forest"
    - "[FP=11] Rainbow"
    - "[FP=12] Rainbow bands"
    - "[FP=13] Sunset"
    - "[FP=14] Rivendell"
    - "[FP=15] Breeze"
    - "[FP=16] Red & Blue"
    - "[FP=17] Yellowout"
    - "[FP=18] Analoguous"
    - "[FP=19] Splash"
    - "[FP=20] Pastel"
    - "[FP=21] Sunset 2"
    - "[FP=22] Beech"
    - "[FP=23] Vintage"
    - "[FP=24] Departure"
    - "[FP=25] Landscape"
    - "[FP=26] Beach"
    - "[FP=27] Sherbet"
    - "[FP=28] Hult"
    - "[FP=29] Hult 64"
    - "[FP=30] Drywet"
    - "[FP=31] Jul"
    - "[FP=32] Grintage"
    - "[FP=33] Rewhi"
    - "[FP=34] Tertiary"
    - "[FP=35] Fire"
    - "[FP=36] Icefire"
    - "[FP=37] Cyane"
    - "[FP=38] Light Pink"
    - "[FP=39] Autumn"
    - "[FP=40] Magenta"

wled_presets:
  options:
    - "[PL=01] Preset 1"
    - "[PL=02] Preset 2"
    - "[PL=03] Preset 3"
    - "[PL=04] Preset 4"
    - "[PL=05] Preset 5"
    - "[PL=06] Preset 6"
    - "[PL=07] Preset 7"
    - "[PL=08] Preset 8"
    - "[PL=09] Preset 9"
    - "[PL=10] Preset 10"
    - "[PL=11] Preset 11"
    - "[PL=12] Preset 12"
    - "[PL=13] Preset 13"
    - "[PL=14] Preset 14"
    - "[PL=15] Preset 15"
    - "[PL=16] Preset 16"
```
I was not sure if these were used in the NodeRed flows (I've never used it) so did not make a PR.
